### PR TITLE
Various enhancements

### PR DESCRIPTION
**Pull request by vrdhn**
Hi. Thanks for the good work (-:
Looks like i need to use this so going to enhance it a bit.
The first change ... making it run on python3

### CODE REVIEW

**Review by compor — CHANGES_REQUESTED** [review]
Thanks for the enhancements! :smile:

I don't mind having this included, but could you please make it an option controlled via the command-line?
e.g.  `-s` for sorted and `-s 10` for sorting and displaying the first 10 entries.

I was using cmd-line tools to do that so far (sort, head, etc) and I'd still like to have all results available

**Comment by compor** [comment]
Also, if the changes are thematically different enough, please keep them in separate PRs.
I know this is just a rough cut script but it helps me track down what is changed properly :smile:

**Comment by vrdhn** [comment]
I generated the PR with only first checkin ( has_key -> in ). The other one was purely for my own fork.
However looks like github just keeps appending checkins it to PR. I was not aware of that .  
It it's possible , just take the first diff ; if now, just close the PR.

Thanks

**Comment by compor** [comment]
I can't do that via the github UI, so I'll just close it.

**Pull request closed without merging**
